name: Integracion Continua (CI)
on:
  push:
    branches: [main]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', '20']
    steps:
      - name: 1 obtener codigo
        uses: actions/checkout@v4
      - name: 2 configurar node.js(${{matrix.node-version}})
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
      - name: 3 instalar dependencias
        run: npm ci
      - name: 4 probar el codigo
        run: npm test
  deploy:
    needs: [build_and_test]
    runs-on:
      ubuntu-latest
    steps:
      - name: 1. Descargar el codigo
        uses: actions/checkout@v4
      - name: 3. despliegue
        run: echo "despliegue exitoso"
    
